### PR TITLE
Remove deprecated governance signing type

### PR DESCRIPTION
**Pull request by achamayou**
HTTP signing has been dropped from CCF in 5.x.

### CODE REVIEW

**Review by andpiccione — APPROVED** [review]

**Comment by achamayou** [comment]
@andpiccione this seems to be blocked on the license/cla check, do you know if there is a way to force that to run?

**Comment by andpiccione** [comment]
Changed the pipeline settings to enable PR builds on forks, retrying

**Comment by ivarprudnikov** [comment]
Removed the license/cla protection from the main branch.

**Pull request merged**
