### PR TITLE
Update to CCF 4.0.16

### PR DESCRIPTION
**Pull request by prathod09**
- Update to CCF 4.0.16

### CODE REVIEW

**Comment by andpiccione** [comment]
Build is failing because the `4.0.16` version cannot be found:

image

Indeed, there is no new version available in PyPi

image

I see that the [CCF github action that publishes the package](https://github.com/microsoft/CCF/actions/runs/8344512468) has failed, I'm checking with the CCF team on this

image

**Comment by andpiccione** [comment]
CCF team has fixed the GH action and the package has been published. I'm triggering a new build:

image

**Comment by prathod09** [comment]
> CCF team has fixed the GH action and the package has been published. I'm triggering a new build:
> 
> image

**Comment by prathod09** [comment]
Thanks Andrea! Looks like all the checks have passed now.

**Review by andpiccione — APPROVED** [review]

**Pull request merged**
